server:
  port: 8083

#mongodb://localhost:27017
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microdb

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

